### PR TITLE
Challenge card & Navbar updates

### PR DESCRIPTION
**Pull request by TammyTee**
@binarymason 
Added changes to challenge card. Resolves issue #24 and issue #28 
challenge-card

### CODE REVIEW

**Comment by TammyTee** [comment]
This PR now includes addition of the FAQ link to the navbar (issue #50).

**Comment by binarymason** [comment]
@TammyTee, you rock! 🏅 👍 

Because it's typically better practice to have a PR be focused on just one issue, do you mind splitting this PR for each issue?

I recommend branching off of your current branch, doing an interactive rebase, then dropping the commits that don't apply.

ie:

```
git checkout -b fix-issue-777
git rebase -i origin/development
...(select your commits)
git push
```
when you are doing the rebase, for the commits that you want to drop, you will need to change `pick` to `drop`.

Repeat for every issue, starting from this branch, then branching off and removing commits.

Feel free to ping me if you have any questions, and keep up the good work! 💪

**Comment by TammyTee** [comment]
@binarymason 🤦‍♀️ . I thought that was the way I should do it.

So, I'm wondering how I can actually do the rebase. When I start the interactive rebase I can only see the latest commit (c9bbf67). I'm not sure if this is because when I was working on each issue I merged their individual branches with my local `origin/development` branch and deleted them after 😕 .

rebase

Also, for future reference, how do I avoid a commit that I push from being added on to a PR that's already open for a separate issue? Do I have to wait until the PR is closed and merged before pushing other commits?

**Comment by binarymason** [comment]
Doh! looks like I had a brain fart.  You actually want to rebase off of upstream remote

Here are the steps you need to follow. Just ensure you tack on the `-i` to go into interactive mode:
https://github.com/charlottejuniordevs/faq/issues/7#issue-229850372

To answer your question, if things are decoupled, you can remove commits from history from a branch so that branch is focused on one thing.  Here's an example of what I did by `rebase -i upstream/master` from your fork:

```
drop a96a394 Added comment count to challenge card. Resolves issue charlottejuniordevs/client#28
drop 9893919 Added labels to "challenge" cards. Also challengeCard styles.
pick 2833541 Added FAQ nav link. charlottejuniordevs/client#50

# Rebase 52510df..2833541 onto 52510df (3 commands)
#
# Commands:
# p, pick = use commit
# r, reword = use commit, but edit the commit message
# e, edit = use commit, but stop for amending
# s, squash = use commit, but meld into previous commit
# f, fixup = like "squash", but discard this commit's log message
# x, exec = run command (the rest of the line) using shell
# d, drop = remove commit
```

Then you would do `git push` to just push up that specific commit to that branch.  Make sense?

**Comment by TammyTee** [comment]
@binarymason I think I got it! Submitting a PR for each issue now.

**Comment by TammyTee** [comment]
@binarymason Think I did everything right 😬. New PRs have been submitted.

**Comment by binarymason** [comment]
Cool, looks like this PR can safely be closed then.  Great job!

**Pull request closed without merging**
