### PR TITLE
add space between first and last name on leaderboard

### PR DESCRIPTION
**Pull request by jb2718**
@binarymason 
I think this does the trick

### CODE REVIEW

**Comment by binarymason** [comment]
hey make sure you take the @ off your username on challenges.charlottejuniordevs.com for the points to work

**Comment by jb2718** [comment]
Gotcha! - will do

**Comment by binarymason** [comment]
Hi @jb2718 looks like this isn't working on our qa site. 😿  Do you mind opening another PR to fix?
image

**Comment by jb2718** [comment]
Hi @binarymason, 
No problem!  I submitted a new pull request for this issue

**Pull request merged**
